#!/user/bin/env python3

#TODO:
    # Create REGEX FOR PHONE NUMBERS
    # CREATE REGEX FOR EMAIL ADDRESSES
    # GET TEXT OFF CLIPBOARD
    # EXTRA EMAIL/PHONE FROM CLIPBOARD TEXT
    # COPY EXTRACTED TEXT TO CLIPBOARD
